/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package lvq;

import java.io.BufferedReader;
import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.ArrayList;
import java.util.List;
import java.util.Random;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ahmet
 */
public class frame extends javax.swing.JFrame {
    
    

    /**
     * Creates new form frame
     */
    public frame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        noron = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        ogrenme = new javax.swing.JTextField();
        basari = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        aktivasyon = new javax.swing.JComboBox();
        egit = new javax.swing.JButton();
        test = new javax.swing.JButton();
        sil = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        cikti = new javax.swing.JTextArea();
        jLabel4 = new javax.swing.JLabel();
        dosya_adres = new javax.swing.JTextField();
        dosya = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Ogrenme parametreleri", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11), new java.awt.Color(0, 255, 0))); // NOI18N

        jLabel1.setText("nöron sayısı :");

        jLabel2.setText("ogrenme katsayisi :");

        jLabel3.setText("    min basarı oranı:");

        jLabel5.setText("aktivasyon fonksiyonu :");

        aktivasyon.setModel(new javax.swing.DefaultComboBoxModel(new String[] {"bir fonksiyon seciniz","sigmoid", "lineer fonksiyon", "step fonksiyonu ", "Item esik değer fonksiyonu" }));

        egit.setText("egit");
        egit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                egitActionPerformed(evt);
            }
        });

        test.setText("test et");
        test.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                testActionPerformed(evt);
            }
        });

        sil.setText("sil");
        sil.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                silActionPerformed(evt);
            }
        });

        cikti.setColumns(20);
        cikti.setRows(5);
        jScrollPane1.setViewportView(cikti);

        jLabel4.setText("ornekler için dosya sec:");

        dosya.setText("dosya al");
        dosya.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dosyaActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jLabel5)
                            .addComponent(jLabel1)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(aktivasyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dosya_adres, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel1Layout.createSequentialGroup()
                                        .addComponent(egit)
                                        .addGap(18, 18, 18)
                                        .addComponent(test)
                                        .addGap(18, 18, 18)
                                        .addComponent(sil))
                                    .addComponent(noron, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ogrenme, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(basari, javax.swing.GroupLayout.Alignment.LEADING))
                                .addGap(18, 18, 18)
                                .addComponent(dosya, javax.swing.GroupLayout.PREFERRED_SIZE, 91, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 375, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel1Layout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {egit, sil, test});

        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(noron, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(ogrenme, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(basari, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(aktivasyon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(dosya_adres, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(dosya))
                .addGap(42, 42, 42)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(egit)
                    .addComponent(test)
                    .addComponent(sil))
                .addGap(37, 37, 37)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 134, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGap(116, 116, 116))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(41, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void egitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_egitActionPerformed
                basari_orani=Double.parseDouble(basari.getText());
                noronlar=Integer.parseInt(noron.getText());
		girisOku(data, target,dosya_adres.getText());
                s =new String [noronlar];
                rastgele();
                String[] input = {"kirmizi", "mavi"};
                System.out.println(data.get(1));
		Lvq lvq = new Lvq(noronlar, data.get(1).size(), s,Double.parseDouble(ogrenme.getText()),basari_orani);
                
		//cikti.setText(lvq.printWeights());
		
                
		
		System.out.println("egitim çalışması");
                lvq.iterasyon(data, target);
		//lvq.agirliklariYazdir();
                sistem_basarisi=lvq.test_et(data, target);
                int m=2;
                int n = 0;
                while ( sistem_basarisi < basari_orani & n < 5000){
                       System.out.println((m++)+".epoch");
                       lvq.iterasyon(data, target);         
                       System.out.println("egitim çalışması");
                       //lvq.printWeights();
                       sistem_basarisi=lvq.test_et(data, target);
                       System.out.println("---------------------------");
                       n=n+1;
                }
                
                
        
    }//GEN-LAST:event_egitActionPerformed

    private void testActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_testActionPerformed
       cikti.setText("basari orani:");
       cikti.setText("%"+String.valueOf(sistem_basarisi*100)+"   basari orani ");
       
        
        
    }//GEN-LAST:event_testActionPerformed

    public void rastgele(){
           int a;
           for (int i=0; i<noronlar; i++){
           Random r=new Random();
           a=r.nextInt(target.size());
           System.out.println(target.get(a)+"rastgele mi  "+target.size());
           s [i]=target.get(a).toString();
    
    
        }
    
    }
    
    
    private void silActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_silActionPerformed
        
        noron.setText("");
        ogrenme.setText("");
        basari.setText("");
        aktivasyon.setSelectedIndex(0);
    }//GEN-LAST:event_silActionPerformed

    private void dosyaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dosyaActionPerformed
         sec = new JFileChooser();
    filt = new FileNameExtensionFilter("txt dosyalari", "txt");
    sec.addChoosableFileFilter(filt);
    int ret =sec.showDialog(null, "Dosya aç");

    if (ret == JFileChooser.APPROVE_OPTION) {
      File file = sec.getSelectedFile();
      dosya_adres.setText(file.toString());
    }//GEN-LAST:event_dosyaActionPerformed
    }
    /**
     * @param args the command line arguments
     */
   	public static void girisOku(List<List<Double>> giris, List<String> cikis,String adres) {
		try {
			file = new File(adres);
                        System.out.println( file.getPath());
                   
			BufferedReader br = new BufferedReader(new FileReader(file));

			String satir = "";
			//System.out.println(">>>Start reading input...");
			while((satir = br.readLine()) != null) {
				String[] satirlar = satir.split(",");
				List<Double> vector = new ArrayList<Double>();
				for(int i=0; i<satirlar.length; i++) {
					if(i != satirlar.length-1) {
						int d = Integer.parseInt(satirlar[i]);
						vector.add((double)d);
						//System.out.print(d+",");
					} else {
						//int cl = Integer.parseInt(lines[i]);
						cikis.add(satirlar[i]);
						System.out.print(satirlar[i]);
					}
				}
				giris.add(vector);
				//System.out.println();
			}
		} catch (IOException ioe) {
			ioe.printStackTrace();
		}
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JComboBox aktivasyon;
    private javax.swing.JTextField basari;
    private javax.swing.JTextArea cikti;
    private javax.swing.JButton dosya;
    private javax.swing.JTextField dosya_adres;
    private javax.swing.JButton egit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextField noron;
    private javax.swing.JTextField ogrenme;
    private javax.swing.JButton sil;
    private javax.swing.JButton test;
    // End of variables declaration//GEN-END:variables
        private  List<List<Double>> data = new ArrayList<List<Double>>();
	private List<String> target = new ArrayList<String>();
        public double basari_orani;
        public int noronlar;
        private String s [];
        private double sistem_basarisi;
        private JFileChooser sec;
        private FileNameExtensionFilter filt;
        private static File file ;

}

