/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * giris.java
 *
 * Created on 29.Tem.2011, 10:53:04
 */
package deneme1;

import java.awt.Color;
import java.awt.Font;
import java.awt.FontMetrics;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Rectangle;
import java.awt.Shape;
import java.awt.image.ImageObserver;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;
import java.text.AttributedCharacterIterator;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/**
 *
 * @author ahmet
 */
public class girispenceresi extends javax.swing.JFrame {

    /** Creates new form giris */
    public girispenceresi() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jPasswordField1 = new javax.swing.JPasswordField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jLabel1.setText("Kullanıcı Adı");

        jLabel2.setText("Sifre");

        jButton1.setText("Giriş");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(93, 93, 93)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPasswordField1)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField1, javax.swing.GroupLayout.DEFAULT_SIZE, 112, Short.MAX_VALUE))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(120, 120, 120)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(jPasswordField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addComponent(jButton1)
                .addContainerGap(62, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {                                         
    
        kayitla_karsilastir();
   
    
        // TODO add your handling code here:
    }                                        

    
     private void kayitla_karsilastir(){
        try {
            Statement st = baglantiAc();
            ResultSet res = st.executeQuery("select  adi,sifre from kisi");
            boolean bulundu=false;
            if((jTextField1.getText())!="" && (  jPasswordField1.getText())!="")

            {
                while(res.next())
                {
            if((res.getString("adi")).equals(jTextField1.getText())  && (res.getString("sifre")).equals(jPasswordField1.getText())) 
            {
            
                 
                 bulundu=true;
               
                 break;
               
            }
                }
                
               if(bulundu)
               {
                 
                 pencere pen=new pencere();
                 pen.setVisible(true);
                 pen.setTitle("EVRAK KAYIT SİSTEMİ");
                 JOptionPane.showMessageDialog(null, "Başarıyla Giriş Yaptınız...");
                 
               }
  
               else
               {
                    JOptionPane.showMessageDialog(null, "yanlış kullanıcı adı veya şifre");
               }
          
                
               
  }
            else {
                   JOptionPane.showMessageDialog(null, "LÜTFEN TÜM ALANLARI DOLDURUNUZ");
                
            }
            
        } catch (Exception ex) {
                   JOptionPane.showMessageDialog(null, "HATALI GİRİŞ");
        }
       
    }         
      
     
     public static Statement baglantiAc() throws Exception 
     {
     
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsiv","root","1905anka"); //bağlantı açılıyor
        return (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
    }
    
    // Variables declaration - do not modify
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration


}
