
package deneme1;

import com.mysql.jdbc.Statement;
import java.awt.Component;
import java.io.File;
import java.sql.*;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.DefaultListModel;
import javax.swing.JComboBox;
import javax.swing.JFileChooser;
import javax.swing.JList;
import javax.swing.JTextField;
import javax.swing.filechooser.FileFilter;
import javax.swing.filechooser.FileNameExtensionFilter;

/**
 *
 * @author ahmet
 */
public class pencere extends javax.swing.JFrame {
    

    /** Creates new form yenipen */
    public pencere() {
        try {
            initComponents();
        } catch (SQLException ex) {
            Logger.getLogger(pencere.class.getName()).log(Level.SEVERE, null, ex);
        } catch (Exception ex) {
            Logger.getLogger(pencere.class.getName()).log(Level.SEVERE, null, ex);
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() throws SQLException, Exception {

        jPanel2 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel4 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        Konu = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        sayi2 = new javax.swing.JTextField();
        tarih2 = new javax.swing.JTextField();
        konu2 = new javax.swing.JTextField();
        anahtar2 = new javax.swing.JTextField();
        nitelik2 = new javax.swing.JComboBox();
        birim2 = new javax.swing.JComboBox();
        gozat2 = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        modelilgi = new DefaultListModel();
        ilgilistesi = new javax.swing.JList(modelilgi);
        jScrollPane3 = new javax.swing.JScrollPane();
        modelparaf = new DefaultListModel();
        paraflistesi = new javax.swing.JList(modelparaf);
        kaydet2 = new javax.swing.JButton();
        sil2 = new javax.swing.JButton();
        iptal2 = new javax.swing.JButton();
        dosya2 = new javax.swing.JTextField();
        jLabel11 = new javax.swing.JLabel();
       
        paraf = new javax.swing.JComboBox();
        jLabel18 = new javax.swing.JLabel();
        parafİmza = new javax.swing.JComboBox();
        ilgi = new javax.swing.JComboBox();
        parafTarihi = new javax.swing.JTextField();
        parafekle = new javax.swing.JButton();
        ilgiekle = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        sayi1 = new javax.swing.JTextField();
        anahtar1 = new javax.swing.JTextField();
        dosya1 = new javax.swing.JTextField();
        birim1 = new javax.swing.JComboBox();
        jScrollPane1 = new javax.swing.JScrollPane();
        modelhavale = new DefaultListModel();
        havalelistesi = new javax.swing.JList(modelhavale);
        gozat1 = new javax.swing.JButton();
        kaydet1 = new javax.swing.JButton();
        sil1 = new javax.swing.JButton();
        iptal1 = new javax.swing.JButton();
        nitelik1 = new javax.swing.JComboBox();
        konu1 = new javax.swing.JTextField();
        jLabel19 = new javax.swing.JLabel();
        havaleTarihi = new javax.swing.JTextField();
        tarih1 = new javax.swing.JTextField();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1550, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Sorgulama", jPanel4);

        jLabel9.setText("Sayi");

        jLabel10.setText("Tarih");

        Konu.setText("Konu");

        jLabel12.setText("Anahtar Sozcuk");

        jLabel13.setText("Dosya");

        jLabel14.setText("Nitelik");

        jLabel15.setText("Birim");

        jLabel16.setText("İlgi");

        jLabel17.setText("Paraf");
        String mantıksal;
            sta=baglantiAc();
            res=sta.executeQuery("select * from birim");
            while(res.next()){
                if(res.getBoolean("kurumİcimi"))
                    mantıksal="kurum içi";
                else
                    mantıksal="kurum dışı";
                
               
                birim2.addItem(res.getString("birimAdi"));
            }
          
            res=sta.executeQuery("select nitelikAdi from nitelik");
            while(res.next()){
                nitelik2.addItem(res.getString("nitelikAdi"));
            }
        res=sta.executeQuery("select adi ,soyadi from kisi");
             while(res.next()){
                paraf.addItem(res.getString("adi")+"    "+(res.getString("soyadi")));
            }
           res=sta.executeQuery("select sayi from giden_evrak");
           /* ResultSet ilgis=st.executeQuery("select * from ilgi");*/
            while(res.next()){
                ilgi.addItem(res.getString("sayi")+"    "+"SAYILI EVRAK");
            }
            parafİmza.addItem("paraf");
            parafİmza.addItem("imza");
            
        gozat2.setText("Gözat");
        gozat2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gozat2ActionPerformed(evt);
            }
        });

        jScrollPane2.setViewportView(ilgilistesi);

        jScrollPane3.setViewportView(paraflistesi);
        
        kaydet2.setText("Kaydet");
        kaydet2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    kaydet2ActionPerformed(evt);
                } catch (Exception ex) {
                    Logger.getLogger(pencere.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        sil2.setText("Sil");
        sil2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil2ActionPerformed(evt);
            }
        });

        iptal2.setText("İptal");
        iptal2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptal2ActionPerformed(evt);
            }
        });

        jLabel11.setText("Paraf Tarihi");

        jLabel18.setText("Paraf-İmza");

        parafekle.setText("Paraf Ekle");
        parafekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                parafekleActionPerformed(evt,modelparaf);
            }
        });

        ilgiekle.setText("İlgi Ekle");
        ilgiekle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    ilgiekleActionPerformed(evt,modelilgi);
                } catch (Exception ex) {
                    Logger.getLogger(pencere.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(62, 62, 62)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel10)
                    .addComponent(jLabel9)
                    .addComponent(jLabel12)
                    .addComponent(jLabel13)
                    .addComponent(jLabel14)
                    .addComponent(jLabel15)
                    .addComponent(jLabel16)
                    .addComponent(jLabel17)
                    .addComponent(jLabel18)
                    .addComponent(jLabel11)
                    .addComponent(Konu))
                .addGap(59, 59, 59)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(parafTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 148, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(parafİmza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(276, 276, 276))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(ilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(paraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(kaydet2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addComponent(sil2, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                            .addComponent(parafekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                            .addComponent(ilgiekle, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 83, Short.MAX_VALUE))
                                        .addGap(18, 18, 18)
                                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 284, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 284, Short.MAX_VALUE)))
                                    .addComponent(iptal2, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addComponent(dosya2)
                                    .addComponent(anahtar2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(konu2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(tarih2, javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(sayi2, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 327, Short.MAX_VALUE))
                                .addGap(18, 18, 18)
                                .addComponent(gozat2)))
                        .addGap(540, 540, 540))
                    .addComponent(nitelik2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(birim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(306, 306, 306))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(sayi2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(tarih2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Konu)
                    .addComponent(konu2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(anahtar2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(dosya2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gozat2))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(nitelik2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel15)
                    .addComponent(birim2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel16)
                        .addComponent(ilgi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(ilgiekle))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel17)
                            .addComponent(paraf, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parafekle))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel18, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(parafİmza, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(parafTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGap(41, 41, 41)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 51, Short.MAX_VALUE)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(kaydet2, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(sil2)
                    .addComponent(iptal2))
                .addGap(30, 30, 30))
        );

        jTabbedPane1.addTab("Giden Evrak", jPanel3);

        jLabel1.setText("Sayi");

        jLabel2.setText("Tarih");

        jLabel3.setText("Konu");

        jLabel4.setText("Anahtar Sozcuk");

        jLabel5.setText("Dosya");

        jLabel6.setText("Nitelik");

        jLabel7.setText("Birim");

        jLabel8.setText("Havale");
            
            
           res =sta.executeQuery("select * from birim");
            while(res.next()){
                
                
               
                birim1.addItem(res.getString("birimAdi"));
            }
           
            res=sta.executeQuery("select nitelikAdi from nitelik");
            while(res.next()){
                nitelik1.addItem(res.getString("nitelikAdi"));
            }
      
        jScrollPane1.setViewportView(havalelistesi);
        res=sta.executeQuery("select adi ,soyadi from kisi");
             while(res.next()){
                modelhavale.addElement(res.getString("adi")+"    "+(res.getString("soyadi")));
            }
            
        gozat1.setText("Gözat");
        gozat1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                gozat1ActionPerformed(evt);
            }
        });

        kaydet1.setText("Kaydet");
        kaydet1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                try {
                    kaydet1ActionPerformed(evt);
                } catch (Exception ex) {
                    Logger.getLogger(pencere.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });

        sil1.setText("Sil");
        sil1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sil1ActionPerformed(evt);
            }
        });

        iptal1.setText("İptal");
        iptal1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                iptal1ActionPerformed(evt);
            }
        });

        

        jLabel19.setText("Havale Tarihi");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(63, 63, 63)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel6)
                    .addComponent(jLabel8)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel7)
                    .addComponent(jLabel19))
                .addGap(57, 57, 57)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(birim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(dosya1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(anahtar1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(tarih1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(konu1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE)
                            .addComponent(nitelik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(sayi1, javax.swing.GroupLayout.DEFAULT_SIZE, 331, Short.MAX_VALUE))
                        .addGap(18, 18, 18)
                        .addComponent(gozat1))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(kaydet1, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(sil1, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(iptal1, javax.swing.GroupLayout.PREFERRED_SIZE, 84, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(havaleTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, 135, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(946, 946, 946))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(sayi1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(tarih1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(konu1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(anahtar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(dosya1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(gozat1))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6)
                    .addComponent(nitelik1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(birim1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(24, 24, 24)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel19)
                            .addComponent(havaleTarihi, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 197, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(kaydet1)
                            .addComponent(sil1)
                            .addComponent(iptal1)))
                    .addComponent(jLabel8))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Gelen Evrak", jPanel1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1555, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 713, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>

    private void gozat1ActionPerformed(java.awt.event.ActionEvent evt) {                                       
    
    dosyaacma = new JFileChooser();
    filt = new FileNameExtensionFilter("pdf files", "pdf");
    dosyaacma.addChoosableFileFilter(filt);
    int ret =dosyaacma.showDialog(null, "Dosya aç");

    if (ret == JFileChooser.APPROVE_OPTION) {
      File file = dosyaacma.getSelectedFile();
      dosya1.setText(file.toString());
    }          
    }                                      
    
    
    
    
    private void gozat2ActionPerformed(java.awt.event.ActionEvent evt) {                                       
    
    dosyaacma = new JFileChooser();
    filt = new FileNameExtensionFilter("pdf files", "pdf");
    dosyaacma.addChoosableFileFilter(filt);
    int ret =dosyaacma.showDialog(null, "Dosya aç");

    if (ret == JFileChooser.APPROVE_OPTION) {
      File file = dosyaacma.getSelectedFile();
      dosya2.setText(file.toString());
    }          
    }        

    private void kaydet1ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
        
        
          gelen_evrak_ekle(nitelikId(nitelik1),birimId(birim1) );
          havale_ekle( havalekisi(),gelenEvrakId());
        
        
        
    }

    private void sil1ActionPerformed(java.awt.event.ActionEvent evt) {
      sayi1.setText("");
      tarih1.setText("");
      konu1.setText("");
      anahtar1.setText("");          
      dosya1.setText("");
      havaleTarihi.setText("");
     /* for(int i=0; i<ilgilistesi.getModel().getSize(); i++){
          modelilgi.setElementAt("", i);
      }
       for(int i=0; i<ilgilistesi.getModel().getSize(); i++){
          modelparaf.setElementAt("", i);
      }*/
   
    }

    
    
    private void iptal1ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }

    private void ilgiekleActionPerformed(java.awt.event.ActionEvent evt,DefaultListModel modelilgi) throws Exception {
    
     String []  s= ilgi.getSelectedItem().toString().split(" ");
       modelilgi.addElement(s[0] );
      
    }

    
    private void parafekleActionPerformed(java.awt.event.ActionEvent evt,DefaultListModel modelparaf) {
       
        modelparaf.addElement( paraf.getSelectedItem()+"        ("+parafİmza.getSelectedItem()+")");
        System.out.println( modelparaf.getElementAt(0).toString());
       String [] dizi= modelparaf.getElementAt(0).toString().split("  " , 2);
        System.out.println(dizi[0]);
        
        System.out.println(dizi[1]);
    }

    private void kaydet2ActionPerformed(java.awt.event.ActionEvent evt) throws Exception {
        /* seciliyap(paraflistesi);
         seciliyap(ilgilistesi);*/
         giden_evrak_ekle(nitelikId(nitelik2) );
         gitdigi_yer_ekle(gidenEvrakId() , birimId(birim2));
         ilgi_ekle(gidensayiId(ilgilistesi)); 
         paraf_ekle(kisiId(paraflistesi),gidenEvrakId(),paraf_imza(paraflistesi));
         
        
        
    }

    private void sil2ActionPerformed(java.awt.event.ActionEvent evt) {
      sayi2.setText("");
      tarih2.setText("");
      konu2.setText("");
      anahtar2.setText("");          
      dosya2.setText("");
      parafTarihi.setText("");
      for(int i=0; i<ilgilistesi.getModel().getSize(); i++){
          modelilgi.setElementAt("", i);
      }
       for(int i=0; i<ilgilistesi.getModel().getSize(); i++){
          modelparaf.setElementAt("", i);
       }
    }  
        
    

    private void iptal2ActionPerformed(java.awt.event.ActionEvent evt) {
        // TODO add your handling code here:
    }    
    
   private static String [] elemanayir(String s1,JList j,String tablo,DefaultListModel d) throws Exception{
     
       sta=baglantiAc();
       res=sta.executeQuery("select * from "+tablo);
       String s []=new String[j.getModel().getSize()];
       for(int i=0; i<j.getModel().getSize(); i++){
        while(res.next()){
           if((d.getElementAt(i).toString()).contains(res.getString(s1))){
                s[i]=res.getString(s1);
                res.first();
                break;
           }
               }}
        return s;
    }
    
 private static void seciliyap(JList j){
    
           for (int i=0; i<j.getModel().getSize(); i++){
               j.setSelectedIndex(i);
           }
    } 
   
   
   
 public static Statement baglantiAc() throws Exception 
     {
     
        Class.forName("com.mysql.jdbc.Driver").newInstance();
        Connection conn = (Connection) DriverManager.getConnection("jdbc:mysql://localhost/arsiv","root","1905anka"); //bağlantı açılıyor
        return (Statement) conn.createStatement(ResultSet.TYPE_SCROLL_INSENSITIVE,ResultSet.CONCUR_UPDATABLE);
    }
   private static void giden_evrak_ekle(int nitelik) throws Exception{
               sta=baglantiAc();
              sta.executeUpdate("insert into giden_evrak(sayi,konu,dosya,keyword,nitelikId) values('" +
              sayi2.getText()+"','"+
              konu2.getText()+"','"+ 
              dosya2.getText()+"','"+
              anahtar2.getText() +"','"+nitelik+"')");
   }         
   private static void gitdigi_yer_ekle(int giden,int birim) throws Exception{
               sta=baglantiAc();
              sta.executeUpdate("insert into gidenevrakgittigiyer(gidenEvrakId,birimNo) values('" +
              giden+"','"+
              birim+"')");  
             
  
   }
  
  private static void paraf_ekle(int [] kisi,int giden ,String [] paraf ) throws Exception{
               sta=baglantiAc();
              for(int i=0; i<kisi.length; i++){
              sta.executeUpdate("insert into paraf(kisiId,gidenEvrakId,imzaParaf) values('" +
               kisi[i]+"','"+
              giden+"','"+paraf[i]+"')");
  }
  
  }
  private static void ilgi_ekle(int [] giden) throws Exception{
              sta=baglantiAc();
              
              for(int i=0; i<giden.length; i++){
              sta.executeUpdate("insert into ilgi(gidenEvrakId,gelenGiden) values('" +
            
     giden[i]+"','"+ "gelen"+"')");
  }
  }
 
 
 private static int  nitelikId(JComboBox nitelik) throws Exception{
 
            int  ntlkıd = 1;
            sta=baglantiAc();
            res=sta.executeQuery("select * from nitelik");
            while(res.next()){
                if((nitelik.getSelectedItem()).equals( res.getString("nitelikAdi"))  ){
                    ntlkıd=res.getInt("nitelikId");
               
                    break;
            }
            }
            return ntlkıd;
 }            
 
     
   private static int birimId(JComboBox birim) throws Exception{
       int birimıd=1 ;
           sta=baglantiAc();
         
            res=sta.executeQuery("select * from birim");
            while(res.next()){
            if((birim.getSelectedItem()).equals(res.getString("birimAdi"))  ){
                birimıd=res.getInt("birimNo");
                break;
            }
            }
            return birimıd;
   }
   
  private static int [] kisiId(JList j) throws Exception{
       
          Statement st=baglantiAc();
          ResultSet rs;
          
          rs=st.executeQuery("select * from kisi");
           String [] adi=elemanayir("adi",j,"kisi",modelparaf);
          String [] soyadi=elemanayir("soyadi",j,"kisi",modelparaf);
          int [] boyut =new int[j.getModel().getSize()];
         // int [] boyut =new int[paraflistesi.getModel().getSize()];
          for(int i=0; i< j.getModel().getSize(); i++){
              
           // a=elemanayir("adi")+elemanayir("soyadi");
            while(rs.next()){
           
              
              if(((adi[i]).toString()+soyadi[i].toString()).equals(rs.getString("adi")+rs.getString("soyadi"))  ){
                boyut[i]=rs.getInt("kisiId");
                res.first();
                break;
                
            }
            }
}
          return boyut;   
   }

  
  
  private static  int gidenEvrakId() throws Exception, Exception, Exception{
       int gidenıd=1;
           sta=baglantiAc();
            res=sta.executeQuery("select gidenEvrakId from giden_evrak");
         while(res.next()){
            gidenıd=res.getInt("gidenEvrakId");
             }
           return gidenıd;
  }         
            
   private static  int gelenEvrakId() throws Exception{
       int gidenıd=1;
            sta=baglantiAc();
            ResultSet res=sta.executeQuery("select gelenEvrakId from gelen_evrak");
            while(res.next()){
            gidenıd=res.getInt("gelenEvrakId");
             }
           return gidenıd;
  }         
    
  
    private static String [] paraf_imza(JList j) throws Exception{
          //String [] imza=elemanayir("imzaParaf",j,"paraf",modelparaf);
          String [] boyut =new String[j.getModel().getSize()];
        
          for(int i=0; i< j.getModel().getSize(); i++){
             
                if(((modelparaf.getElementAt(i).toString()).contains("paraf"))  ){
                    boyut[i]="imza";
                    continue;}
                
                else {
                    if(((modelparaf.getElementAt(i).toString()).contains("imza"))){
                    boyut[i]="paraf";
                    continue;
                    }
                    }
                
                
                
            
            }

          return boyut;   
   }
   
   private static  int [] gidensayiId(JList j) throws Exception{
   
          sta=baglantiAc();
          res=sta.executeQuery("select * from giden_evrak");
          int [] boyut =new int [j.getModel().getSize()];
          for(int i=0; i< j.getModel().getSize(); i++){
            while(res.next()){
           
                if((modelilgi.getElementAt(i).toString()).equals(res.getString("sayi"))  ){
                    boyut[i]=res.getInt("gidenEvrakId");
                    res.first();
                    break;
                
            }
            }
          }
          return boyut;  
   
   }
private static void gelen_evrak_ekle(int nitelik,int birim) throws Exception{
               sta=baglantiAc();
              sta.executeUpdate("insert into gelen_evrak(sayi,konu,dosya,keyword,nitelikId,birimNo) values('" +
              sayi1.getText()+"','"+
              konu1.getText()+"','"+ 
              dosya1.getText()+"','"+
              anahtar1.getText() +"','"+
              nitelik+"','"+birim+"')");
   }       
 
 private static void havale_ekle(int [] kisi,int giden ) throws Exception{
               sta=baglantiAc();
              for(int i=0; i<kisi.length; i++){
              sta.executeUpdate("insert into havale(kisiId,gelenEvrakId,havaleTarihi) values('" +
               kisi[i]+"','"+
              giden+"','"+ havaleTarihi.getText()+"')");

  }
  
  }
 
 
 private static int [] havalekisi() throws Exception{
 
  sta=baglantiAc();
          res=sta.executeQuery("select * from kisi");
          int [] boyut =new int [havalelistesi.getModel().getSize()];
          for(int i=0; i< havalelistesi.getModel().getSize(); i++){
            while(res.next()){
           
                if((modelhavale.getElementAt(i).toString()).equals(res.getString("adi")+"    "+(res.getString("soyadi")))  ){
                    boyut[i]=res.getInt("kisiId");
                    System.out.println(boyut[i]);
                    res.first();
                    break;
                
            }
            }
          }
          return boyut;
 }
 
 
  private static String [] gelen_gidenbul(JList j) throws Exception{
       
          Statement st=baglantiAc();
          ResultSet rs;
          
          rs=st.executeQuery("select * from ilgi");
           String [] imza=elemanayir("gelenGiden",j,"ilgi",modelilgi);
          
          String [] boyut =new String[j.getModel().getSize()];
        
          for(int i=0; i< j.getModel().getSize(); i++){
              while(rs.next()){
                if((imza[i]).equals(rs.getString("gelenGiden"))  ){
                boyut[i]=rs.getString("gelenGiden");
                res.first();
                break;
                
            }
            }
}
          return boyut;   
   }
 
 
    
    private javax.swing.JLabel Konu;
    private static javax.swing.JTextField anahtar1;
    private static javax.swing.JTextField anahtar2;
    private static  javax.swing.JComboBox birim1;
    private static javax.swing.JComboBox birim2;
    private static javax.swing.JTextField dosya1;
    private static javax.swing.JTextField dosya2;
    private javax.swing.JButton gozat1;
    private javax.swing.JButton gozat2;
    private static javax.swing.JTextField havaleTarihi;
    private static javax.swing.JList havalelistesi;
    private static  javax.swing.JComboBox ilgi;
    private javax.swing.JButton ilgiekle;
    private static javax.swing.JList ilgilistesi;
    private javax.swing.JButton iptal1;
    private javax.swing.JButton iptal2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JButton kaydet1;
    private javax.swing.JButton kaydet2;
    private static javax.swing.JTextField konu1;
    private static javax.swing.JTextField konu2;
    private static javax.swing.JComboBox nitelik1;
     private static javax.swing.JComboBox nitelik2;
    private static JTextField parafTarihi;
    private static javax.swing.JButton sil1;
    private static javax.swing.JButton sil2;
    private static javax.swing.JButton parafekle;
    private static  javax.swing.JComboBox paraf;
    private static  javax.swing.JComboBox parafİmza;
    private static javax.swing.JList paraflistesi;
    private static javax.swing.JTextField sayi1;
    private static javax.swing.JTextField sayi2;
    private static javax.swing.JTextField tarih1;
    private static javax.swing.JTextField tarih2;
    private static ResultSet res;
    private static Statement sta;
    private JFileChooser dosyaacma;
    private FileFilter filt;
    private static DefaultListModel modelhavale;
    private static DefaultListModel modelilgi ;
    private static DefaultListModel modelparaf;
    
    
    
    
   

}